import { prisma } from "../lib/prisma.js";

const SEASON = 2025;

const rows = [
  // AFC EAST
  {
    season: SEASON,
    conference: "AFC",
    division: "AFC East",
    team: "New England Patriots",
    w: 14,
    l: 3,
    t: 0,
    pct: 0.824,
    pf: 490,
    pa: 320,
    net: 170,
    clinched: ["x", "z"],
  },
  {
    season: SEASON,
    conference: "AFC",
    division: "AFC East",
    team: "Buffalo Bills",
    w: 12,
    l: 5,
    t: 0,
    pct: 0.706,
    pf: 481,
    pa: 365,
    net: 116,
    clinched: ["x", "y"],
  },
  {
    season: SEASON,
    conference: "AFC",
    division: "AFC East",
    team: "Miami Dolphins",
    w: 7,
    l: 10,
    t: 0,
    pct: 0.412,
    pf: 347,
    pa: 424,
    net: -77,
    clinched: [],
  },
  {
    season: SEASON,
    conference: "AFC",
    division: "AFC East",
    team: "New York Jets",
    w: 3,
    l: 14,
    t: 0,
    pct: 0.176,
    pf: 300,
    pa: 503,
    net: -203,
    clinched: [],
  },

  // AFC NORTH
  {
    season: SEASON,
    conference: "AFC",
    division: "AFC North",
    team: "Pittsburgh Steelers",
    w: 10,
    l: 7,
    t: 0,
    pct: 0.588,
    pf: 397,
    pa: 387,
    net: 10,
    clinched: ["x", "z"],
  },
  {
    season: SEASON,
    conference: "AFC",
    division: "AFC North",
    team: "Baltimore Ravens",
    w: 8,
    l: 9,
    t: 0,
    pct: 0.471,
    pf: 424,
    pa: 398,
    net: 26,
    clinched: [],
  },
  {
    season: SEASON,
    conference: "AFC",
    division: "AFC North",
    team: "Cincinnati Bengals",
    w: 6,
    l: 11,
    t: 0,
    pct: 0.353,
    pf: 414,
    pa: 492,
    net: -78,
    clinched: [],
  },
  {
    season: SEASON,
    conference: "AFC",
    division: "AFC North",
    team: "Cleveland Browns",
    w: 5,
    l: 12,
    t: 0,
    pct: 0.294,
    pf: 279,
    pa: 379,
    net: -100,
    clinched: [],
  },

  // AFC SOUTH
  {
    season: SEASON,
    conference: "AFC",
    division: "AFC South",
    team: "Jacksonville Jaguars",
    w: 13,
    l: 4,
    t: 0,
    pct: 0.765,
    pf: 474,
    pa: 336,
    net: 138,
    clinched: ["x", "z"],
  },
  {
    season: SEASON,
    conference: "AFC",
    division: "AFC South",
    team: "Houston Texans",
    w: 12,
    l: 5,
    t: 0,
    pct: 0.706,
    pf: 404,
    pa: 295,
    net: 109,
    clinched: ["x", "y"],
  },
  {
    season: SEASON,
    conference: "AFC",
    division: "AFC South",
    team: "Indianapolis Colts",
    w: 8,
    l: 9,
    t: 0,
    pct: 0.471,
    pf: 466,
    pa: 412,
    net: 54,
    clinched: [],
  },
  {
    season: SEASON,
    conference: "AFC",
    division: "AFC South",
    team: "Tennessee Titans",
    w: 3,
    l: 14,
    t: 0,
    pct: 0.176,
    pf: 284,
    pa: 478,
    net: -194,
    clinched: [],
  },

  // AFC WEST
  {
    season: SEASON,
    conference: "AFC",
    division: "AFC West",
    team: "Denver Broncos",
    w: 14,
    l: 3,
    t: 0,
    pct: 0.824,
    pf: 401,
    pa: 311,
    net: 90,
    clinched: ["x", "z", "STAR"],
  },
  {
    season: SEASON,
    conference: "AFC",
    division: "AFC West",
    team: "Los Angeles Chargers",
    w: 11,
    l: 6,
    t: 0,
    pct: 0.647,
    pf: 368,
    pa: 340,
    net: 28,
    clinched: ["x", "y"],
  },
  {
    season: SEASON,
    conference: "AFC",
    division: "AFC West",
    team: "Kansas City Chiefs",
    w: 6,
    l: 11,
    t: 0,
    pct: 0.353,
    pf: 362,
    pa: 328,
    net: 34,
    clinched: [],
  },
  {
    season: SEASON,
    conference: "AFC",
    division: "AFC West",
    team: "Las Vegas Raiders",
    w: 3,
    l: 14,
    t: 0,
    pct: 0.176,
    pf: 241,
    pa: 432,
    net: -191,
    clinched: [],
  },

  // NFC EAST
  {
    season: SEASON,
    conference: "NFC",
    division: "NFC East",
    team: "Philadelphia Eagles",
    w: 11,
    l: 6,
    t: 0,
    pct: 0.647,
    pf: 379,
    pa: 325,
    net: 54,
    clinched: ["x", "z"],
  },
  {
    season: SEASON,
    conference: "NFC",
    division: "NFC East",
    team: "Dallas Cowboys",
    w: 7,
    l: 9,
    t: 1,
    pct: 0.441,
    pf: 471,
    pa: 511,
    net: -40,
    clinched: [],
  },
  {
    season: SEASON,
    conference: "NFC",
    division: "NFC East",
    team: "Washington Commanders",
    w: 5,
    l: 12,
    t: 0,
    pct: 0.294,
    pf: 356,
    pa: 451,
    net: -95,
    clinched: [],
  },
  {
    season: SEASON,
    conference: "NFC",
    division: "NFC East",
    team: "New York Giants",
    w: 4,
    l: 13,
    t: 0,
    pct: 0.235,
    pf: 381,
    pa: 439,
    net: -58,
    clinched: [],
  },

  // NFC NORTH
  {
    season: SEASON,
    conference: "NFC",
    division: "NFC North",
    team: "Chicago Bears",
    w: 11,
    l: 6,
    t: 0,
    pct: 0.647,
    pf: 441,
    pa: 415,
    net: 26,
    clinched: ["x", "z"],
  },
  {
    season: SEASON,
    conference: "NFC",
    division: "NFC North",
    team: "Green Bay Packers",
    w: 9,
    l: 7,
    t: 1,
    pct: 0.559,
    pf: 391,
    pa: 360,
    net: 31,
    clinched: ["x", "y"],
  },
  {
    season: SEASON,
    conference: "NFC",
    division: "NFC North",
    team: "Minnesota Vikings",
    w: 9,
    l: 8,
    t: 0,
    pct: 0.529,
    pf: 344,
    pa: 333,
    net: 11,
    clinched: [],
  },
  {
    season: SEASON,
    conference: "NFC",
    division: "NFC North",
    team: "Detroit Lions",
    w: 9,
    l: 8,
    t: 0,
    pct: 0.529,
    pf: 481,
    pa: 413,
    net: 68,
    clinched: [],
  },

  // NFC SOUTH
  {
    season: SEASON,
    conference: "NFC",
    division: "NFC South",
    team: "Carolina Panthers",
    w: 8,
    l: 9,
    t: 0,
    pct: 0.471,
    pf: 311,
    pa: 380,
    net: -69,
    clinched: ["x", "z"],
  },
  {
    season: SEASON,
    conference: "NFC",
    division: "NFC South",
    team: "Tampa Bay Buccaneers",
    w: 8,
    l: 9,
    t: 0,
    pct: 0.471,
    pf: 380,
    pa: 411,
    net: -31,
    clinched: [],
  },
  {
    season: SEASON,
    conference: "NFC",
    division: "NFC South",
    team: "Atlanta Falcons",
    w: 8,
    l: 9,
    t: 0,
    pct: 0.471,
    pf: 353,
    pa: 401,
    net: -48,
    clinched: [],
  },
  {
    season: SEASON,
    conference: "NFC",
    division: "NFC South",
    team: "New Orleans Saints",
    w: 6,
    l: 11,
    t: 0,
    pct: 0.353,
    pf: 306,
    pa: 383,
    net: -77,
    clinched: [],
  },

  // NFC WEST
  {
    season: SEASON,
    conference: "NFC",
    division: "NFC West",
    team: "Seattle Seahawks",
    w: 14,
    l: 3,
    t: 0,
    pct: 0.824,
    pf: 483,
    pa: 292,
    net: 191,
    clinched: ["x", "z", "STAR"],
  },
  {
    season: SEASON,
    conference: "NFC",
    division: "NFC West",
    team: "Los Angeles Rams",
    w: 12,
    l: 5,
    t: 0,
    pct: 0.706,
    pf: 518,
    pa: 346,
    net: 172,
    clinched: ["x", "y"],
  },
  {
    season: SEASON,
    conference: "NFC",
    division: "NFC West",
    team: "San Francisco 49ers",
    w: 12,
    l: 5,
    t: 0,
    pct: 0.706,
    pf: 437,
    pa: 371,
    net: 66,
    clinched: ["x", "y"],
  },
  {
    season: SEASON,
    conference: "NFC",
    division: "NFC West",
    team: "Arizona Cardinals",
    w: 3,
    l: 14,
    t: 0,
    pct: 0.176,
    pf: 355,
    pa: 488,
    net: -133,
    clinched: [],
  },
];

async function main() {
  console.log(`Restoring standings for season ${SEASON}...`);

  await prisma.standingsRow.deleteMany({
    where: { season: SEASON },
  });

  await prisma.standingsRow.createMany({
    data: rows,
  });

  console.log(`Inserted ${rows.length} standings rows.`);
}

main()
  .catch((err) => {
    console.error("restoreStandings2025 failed:", err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });