import { prisma } from "../lib/prisma.js";

const SEASON = 2025;

const week1 = [
  {
    season: SEASON,
    week: 1,
    gameType: "REG",
    kickoffAt: new Date("2025-09-07T17:00:00.000Z"),
    awayTeam: "LAR",
    homeTeam: "DET",
    awayScore: 17,
    homeScore: 24,
    status: "FINAL",
  },
  {
    season: SEASON,
    week: 1,
    gameType: "REG",
    kickoffAt: new Date("2025-09-07T17:00:00.000Z"),
    awayTeam: "SF",
    homeTeam: "KC",
    awayScore: 28,
    homeScore: 31,
    status: "FINAL",
  },
  {
    season: SEASON,
    week: 1,
    gameType: "REG",
    kickoffAt: new Date("2025-09-07T17:00:00.000Z"),
    awayTeam: "DAL",
    homeTeam: "PHI",
    awayScore: 21,
    homeScore: 27,
    status: "FINAL",
  },
  {
    season: SEASON,
    week: 1,
    gameType: "REG",
    kickoffAt: new Date("2025-09-07T17:00:00.000Z"),
    awayTeam: "NYJ",
    homeTeam: "BUF",
    awayScore: 14,
    homeScore: 30,
    status: "FINAL",
  },
  {
    season: SEASON,
    week: 1,
    gameType: "REG",
    kickoffAt: new Date("2025-09-07T20:25:00.000Z"),
    awayTeam: "BAL",
    homeTeam: "CIN",
    awayScore: 20,
    homeScore: 17,
    status: "FINAL",
  },
  {
    season: SEASON,
    week: 1,
    gameType: "REG",
    kickoffAt: new Date("2025-09-07T20:25:00.000Z"),
    awayTeam: "MIA",
    homeTeam: "NE",
    awayScore: 27,
    homeScore: 21,
    status: "FINAL",
  },
  {
    season: SEASON,
    week: 1,
    gameType: "REG",
    kickoffAt: new Date("2025-09-07T20:25:00.000Z"),
    awayTeam: "GB",
    homeTeam: "CHI",
    awayScore: 24,
    homeScore: 20,
    status: "FINAL",
  },
  {
    season: SEASON,
    week: 1,
    gameType: "REG",
    kickoffAt: new Date("2025-09-07T20:25:00.000Z"),
    awayTeam: "HOU",
    homeTeam: "JAX",
    awayScore: 23,
    homeScore: 26,
    status: "FINAL",
  },
  {
    season: SEASON,
    week: 1,
    gameType: "REG",
    kickoffAt: new Date("2025-09-08T00:20:00.000Z"),
    awayTeam: "MIN",
    homeTeam: "NO",
    awayScore: null,
    homeScore: null,
    status: "SCHEDULED",
  },
  {
    season: SEASON,
    week: 1,
    gameType: "REG",
    kickoffAt: new Date("2025-09-08T00:20:00.000Z"),
    awayTeam: "LAC",
    homeTeam: "LV",
    awayScore: null,
    homeScore: null,
    status: "SCHEDULED",
  },
  {
    season: SEASON,
    week: 1,
    gameType: "REG",
    kickoffAt: new Date("2025-09-08T00:20:00.000Z"),
    awayTeam: "SEA",
    homeTeam: "ARI",
    awayScore: null,
    homeScore: null,
    status: "SCHEDULED",
  },
  {
    season: SEASON,
    week: 1,
    gameType: "REG",
    kickoffAt: new Date("2025-09-08T00:20:00.000Z"),
    awayTeam: "ATL",
    homeTeam: "TB",
    awayScore: null,
    homeScore: null,
    status: "SCHEDULED",
  },
  {
    season: SEASON,
    week: 1,
    gameType: "REG",
    kickoffAt: new Date("2025-09-09T00:15:00.000Z"),
    awayTeam: "CLE",
    homeTeam: "PIT",
    awayScore: null,
    homeScore: null,
    status: "SCHEDULED",
  },
  {
    season: SEASON,
    week: 1,
    gameType: "REG",
    kickoffAt: new Date("2025-09-09T00:15:00.000Z"),
    awayTeam: "IND",
    homeTeam: "TEN",
    awayScore: null,
    homeScore: null,
    status: "SCHEDULED",
  },
  {
    season: SEASON,
    week: 1,
    gameType: "REG",
    kickoffAt: new Date("2025-09-09T00:15:00.000Z"),
    awayTeam: "WAS",
    homeTeam: "NYG",
    awayScore: null,
    homeScore: null,
    status: "SCHEDULED",
  },
  {
    season: SEASON,
    week: 1,
    gameType: "REG",
    kickoffAt: new Date("2025-09-09T00:15:00.000Z"),
    awayTeam: "CAR",
    homeTeam: "DEN",
    awayScore: null,
    homeScore: null,
    status: "SCHEDULED",
  },
];

const week2 = [
  {
    season: SEASON,
    week: 2,
    gameType: "REG",
    kickoffAt: new Date("2027-09-16T17:00:00.000Z"),
    awayTeam: "BUF",
    homeTeam: "MIA",
    awayScore: null,
    homeScore: null,
    status: "SCHEDULED",
  },
  {
    season: SEASON,
    week: 2,
    gameType: "REG",
    kickoffAt: new Date("2027-09-16T17:00:00.000Z"),
    awayTeam: "NE",
    homeTeam: "NYJ",
    awayScore: null,
    homeScore: null,
    status: "SCHEDULED",
  },
  {
    season: SEASON,
    week: 2,
    gameType: "REG",
    kickoffAt: new Date("2027-09-16T17:00:00.000Z"),
    awayTeam: "BAL",
    homeTeam: "CLE",
    awayScore: null,
    homeScore: null,
    status: "SCHEDULED",
  },
  {
    season: SEASON,
    week: 2,
    gameType: "REG",
    kickoffAt: new Date("2027-09-16T17:00:00.000Z"),
    awayTeam: "PIT",
    homeTeam: "CIN",
    awayScore: null,
    homeScore: null,
    status: "SCHEDULED",
  },
  {
    season: SEASON,
    week: 2,
    gameType: "REG",
    kickoffAt: new Date("2027-09-16T20:25:00.000Z"),
    awayTeam: "HOU",
    homeTeam: "IND",
    awayScore: null,
    homeScore: null,
    status: "SCHEDULED",
  },
  {
    season: SEASON,
    week: 2,
    gameType: "REG",
    kickoffAt: new Date("2027-09-16T20:25:00.000Z"),
    awayTeam: "TEN",
    homeTeam: "JAX",
    awayScore: null,
    homeScore: null,
    status: "SCHEDULED",
  },
  {
    season: SEASON,
    week: 2,
    gameType: "REG",
    kickoffAt: new Date("2027-09-16T20:25:00.000Z"),
    awayTeam: "KC",
    homeTeam: "LV",
    awayScore: null,
    homeScore: null,
    status: "SCHEDULED",
  },
  {
    season: SEASON,
    week: 2,
    gameType: "REG",
    kickoffAt: new Date("2027-09-16T20:25:00.000Z"),
    awayTeam: "LAC",
    homeTeam: "DEN",
    awayScore: null,
    homeScore: null,
    status: "SCHEDULED",
  },
  {
    season: SEASON,
    week: 2,
    gameType: "REG",
    kickoffAt: new Date("2027-09-17T00:20:00.000Z"),
    awayTeam: "DAL",
    homeTeam: "WAS",
    awayScore: null,
    homeScore: null,
    status: "SCHEDULED",
  },
  {
    season: SEASON,
    week: 2,
    gameType: "REG",
    kickoffAt: new Date("2027-09-17T00:20:00.000Z"),
    awayTeam: "PHI",
    homeTeam: "NYG",
    awayScore: null,
    homeScore: null,
    status: "SCHEDULED",
  },
  {
    season: SEASON,
    week: 2,
    gameType: "REG",
    kickoffAt: new Date("2027-09-17T00:20:00.000Z"),
    awayTeam: "GB",
    homeTeam: "MIN",
    awayScore: null,
    homeScore: null,
    status: "SCHEDULED",
  },
  {
    season: SEASON,
    week: 2,
    gameType: "REG",
    kickoffAt: new Date("2027-09-17T00:20:00.000Z"),
    awayTeam: "CHI",
    homeTeam: "DET",
    awayScore: null,
    homeScore: null,
    status: "SCHEDULED",
  },
  {
    season: SEASON,
    week: 2,
    gameType: "REG",
    kickoffAt: new Date("2027-09-18T00:15:00.000Z"),
    awayTeam: "ATL",
    homeTeam: "CAR",
    awayScore: null,
    homeScore: null,
    status: "SCHEDULED",
  },
  {
    season: SEASON,
    week: 2,
    gameType: "REG",
    kickoffAt: new Date("2027-09-18T00:15:00.000Z"),
    awayTeam: "NO",
    homeTeam: "TB",
    awayScore: null,
    homeScore: null,
    status: "SCHEDULED",
  },
  {
    season: SEASON,
    week: 2,
    gameType: "REG",
    kickoffAt: new Date("2027-09-18T00:15:00.000Z"),
    awayTeam: "SEA",
    homeTeam: "SF",
    awayScore: null,
    homeScore: null,
    status: "SCHEDULED",
  },
  {
    season: SEASON,
    week: 2,
    gameType: "REG",
    kickoffAt: new Date("2027-09-18T00:15:00.000Z"),
    awayTeam: "ARI",
    homeTeam: "LAR",
    awayScore: null,
    homeScore: null,
    status: "SCHEDULED",
  },
];

const week3 = [
  {
    season: SEASON,
    week: 3,
    gameType: "REG",
    kickoffAt: new Date("2027-09-23T17:00:00.000Z"),
    awayTeam: "BUF",
    homeTeam: "NE",
    awayScore: null,
    homeScore: null,
    status: "SCHEDULED",
  },
  {
    season: SEASON,
    week: 3,
    gameType: "REG",
    kickoffAt: new Date("2027-09-23T17:00:00.000Z"),
    awayTeam: "MIA",
    homeTeam: "NYJ",
    awayScore: null,
    homeScore: null,
    status: "SCHEDULED",
  },
  {
    season: SEASON,
    week: 3,
    gameType: "REG",
    kickoffAt: new Date("2027-09-23T17:00:00.000Z"),
    awayTeam: "CIN",
    homeTeam: "BAL",
    awayScore: null,
    homeScore: null,
    status: "SCHEDULED",
  },
  {
    season: SEASON,
    week: 3,
    gameType: "REG",
    kickoffAt: new Date("2027-09-23T17:00:00.000Z"),
    awayTeam: "CLE",
    homeTeam: "PIT",
    awayScore: null,
    homeScore: null,
    status: "SCHEDULED",
  },
  {
    season: SEASON,
    week: 3,
    gameType: "REG",
    kickoffAt: new Date("2027-09-23T20:25:00.000Z"),
    awayTeam: "IND",
    homeTeam: "HOU",
    awayScore: null,
    homeScore: null,
    status: "SCHEDULED",
  },
  {
    season: SEASON,
    week: 3,
    gameType: "REG",
    kickoffAt: new Date("2027-09-23T20:25:00.000Z"),
    awayTeam: "JAX",
    homeTeam: "TEN",
    awayScore: null,
    homeScore: null,
    status: "SCHEDULED",
  },
  {
    season: SEASON,
    week: 3,
    gameType: "REG",
    kickoffAt: new Date("2027-09-23T20:25:00.000Z"),
    awayTeam: "DEN",
    homeTeam: "KC",
    awayScore: null,
    homeScore: null,
    status: "SCHEDULED",
  },
  {
    season: SEASON,
    week: 3,
    gameType: "REG",
    kickoffAt: new Date("2027-09-23T20:25:00.000Z"),
    awayTeam: "LV",
    homeTeam: "LAC",
    awayScore: null,
    homeScore: null,
    status: "SCHEDULED",
  },
  {
    season: SEASON,
    week: 3,
    gameType: "REG",
    kickoffAt: new Date("2027-09-24T00:20:00.000Z"),
    awayTeam: "NYG",
    homeTeam: "DAL",
    awayScore: null,
    homeScore: null,
    status: "SCHEDULED",
  },
  {
    season: SEASON,
    week: 3,
    gameType: "REG",
    kickoffAt: new Date("2027-09-24T00:20:00.000Z"),
    awayTeam: "WAS",
    homeTeam: "PHI",
    awayScore: null,
    homeScore: null,
    status: "SCHEDULED",
  },
  {
    season: SEASON,
    week: 3,
    gameType: "REG",
    kickoffAt: new Date("2027-09-24T00:20:00.000Z"),
    awayTeam: "DET",
    homeTeam: "GB",
    awayScore: null,
    homeScore: null,
    status: "SCHEDULED",
  },
  {
    season: SEASON,
    week: 3,
    gameType: "REG",
    kickoffAt: new Date("2027-09-24T00:20:00.000Z"),
    awayTeam: "MIN",
    homeTeam: "CHI",
    awayScore: null,
    homeScore: null,
    status: "SCHEDULED",
  },
  {
    season: SEASON,
    week: 3,
    gameType: "REG",
    kickoffAt: new Date("2027-09-25T00:15:00.000Z"),
    awayTeam: "CAR",
    homeTeam: "ATL",
    awayScore: null,
    homeScore: null,
    status: "SCHEDULED",
  },
  {
    season: SEASON,
    week: 3,
    gameType: "REG",
    kickoffAt: new Date("2027-09-25T00:15:00.000Z"),
    awayTeam: "TB",
    homeTeam: "NO",
    awayScore: null,
    homeScore: null,
    status: "SCHEDULED",
  },
  {
    season: SEASON,
    week: 3,
    gameType: "REG",
    kickoffAt: new Date("2027-09-25T00:15:00.000Z"),
    awayTeam: "SF",
    homeTeam: "SEA",
    awayScore: null,
    homeScore: null,
    status: "SCHEDULED",
  },
  {
    season: SEASON,
    week: 3,
    gameType: "REG",
    kickoffAt: new Date("2027-09-25T00:15:00.000Z"),
    awayTeam: "LAR",
    homeTeam: "ARI",
    awayScore: null,
    homeScore: null,
    status: "SCHEDULED",
  },
];

const games = [...week1, ...week2, ...week3];

async function main() {
  console.log(`Seeding ${SEASON} season schedule (3 weeks x 16 games)...`);

  await prisma.$transaction([
    prisma.pickEmPick.deleteMany({
      where: {
        game: {
          season: SEASON,
          week: { in: [1, 2, 3] },
        },
      },
    }),
    prisma.pickEmWeekScore.deleteMany({
      where: {
        season: SEASON,
        week: { in: [1, 2, 3] },
      },
    }),
    prisma.game.deleteMany({
      where: {
        season: SEASON,
        week: { in: [1, 2, 3] },
      },
    }),
    prisma.game.createMany({
      data: games,
    }),
  ]);

  const counts = await prisma.game.groupBy({
    by: ["week"],
    where: {
      season: SEASON,
      week: { in: [1, 2, 3] },
    },
    _count: { _all: true },
    orderBy: { week: "asc" },
  });

  console.log("Done.");
  console.table(
    counts.map((row) => ({
      season: SEASON,
      week: row.week,
      games: row._count._all,
    }))
  );
}

main()
  .catch((err) => {
    console.error("Seed failed:", err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });